### PR TITLE
Small changes to I/O handling

### PR DESCRIPTION
**Pull request by jusing-es**
Hi Luis,
I've started contributing to your project.
So far I've only taken care of those:
- get the db path as input
- get output as a file

And I moved the core of the reading from the db to another function (unoriginally called "main", feel free to change all my names!). Hope this is something you find useful. I'll drop you an email for the next steps ;)

### CODE REVIEW

**Review by lmorgadodacosta — APPROVED** [review]

**Review by lmorgadodacosta — CHANGES_REQUESTED** [review]
There seems to be a typo on line 70  (extra "s" at the end of the line).
Can you please check and resubmit?

**Review by lmorgadodacosta — CHANGES_REQUESTED** [review]
same typo on (new) line 70

**Review by lmorgadodacosta — APPROVED** [review]

**Review by lmorgadodacosta — CHANGES_REQUESTED** [review]
I thought I could accept smaller commits, but this is all bundled in a single pull request :p 
Please check the possibly typo on ntumc.dtd and all the rest seems great! thanks :)

**Comment by jusing-es** [comment]
Hi Luis!
I also thought it was possible to have 1 pull request per commit, then I found this https://stackoverflow.com/questions/30337987/github-how-to-send-one-pull-request-per-separate-commit 

I should have fixed the typo and this latest commit is now, I'm afraid, bundled in the same pull request ;)

Thank you for reviewing it!

**Review by lmorgadodacosta — APPROVED** [review]

**Pull request merged**
